language: node_js
node_js:
  - "6"

services:
  - mongod

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node_modules/protractor/bin/webdriver-manager update
  - node_modules/protractor/bin/webdriver-manager start
  - sleep 3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
