language: node_js
node_js:
  - "6"
  - "4"
env:
  - NODE_ENV=development
services:
  - mongodb


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
      - http://hi.linnovate.net/hooks/g2EY2fQo8hDJcEY6D/yzX8NMbtwKSjrdCBqA9q6hLsRHfhi2JLjPaYSjwXzE8Pha3B
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


