language: node_js
node_js:
  - "6"

services:
  - mongodb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "sleep 5"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
