dist: trusty
language: node_js
node_js:
  - "4"
env:
  - NODE_ENV=development
services:
  - mongodb

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb && sudo service elasticsearch restart

install:
  - npm install -g gulp
  - npm install -g bower

before_script:
  - npm install
  - node tools/scripts/postinstall.js
  - gulp sass
