language: node_js

node_js:
  - "6"

services:
  - mongodb

sudo: required  

dist: trusty  

before_install:
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install elasticsearch
  - sudo service elasticsearch start
  - sudo service elasticsearch status
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - echo '{"anonymizedData":true,"token":""}' > ~/.mean
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
