version: '3'

services:
  app:
    build: ./
    image: root
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo/icu
      ELASTICSEARCH_IP: elasticsearch
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:3.6
    volumes:
      - mongodata:/data/db

  elasticsearch:
    image: elasticsearch:5.6
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

volumes:
  mongodata: