version: '3'

services:
  root-app:
    build: .
    image: root-app
    # image: localhost:5000/root-app
    #restart: always
    ports:
      - "3100:3100"
#      - "5858:5858"      
    links:
      - root-db
      - root-elastic
    volumes:
        - ./packages:/usr/src/app/packages
        - ./config:/usr/src/app/config
        - ./tools:/usr/src/app/tools
      #  - ./node_modules:/usr/src/app/node_modules
        # - ./files:/usr/src/app/files
    command: "gulp development"
  root-db:
    image: mongo:3.6.3
    expose:
      - "27017"
  root-elastic:
    image: elasticsearch
    expose:
      - "9200"
