version: '3'

services:
  app:
    image: node:8
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo/icu-dev
    ports:
      - "3100:3000"
    command: "npm run dev"
    user: $UID

  mongo:
    image: mongo:3.6.3

  elastic:
    image: elasticsearch

