name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qayesodot/root:temp
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DHuser }}
        # Container registry password
        password: ${{ secrets.DHpass }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
       
    - name: Push container
      run: docker push qayesodot/root:temp

  publish:
    
    needs: release

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            ~/groot/ docker-compose down
            ~/groot/ git pull origin master
            ~/groot/ docker-compose -f docker-compose.production.yml up -d

            