name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qayesodot/root:temp
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DHuser }}
        # Container registry password
        password: ${{ secrets.DHpass }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
       
    - name: Push container
      run: docker push qayesodot/root:temp
