name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  release:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qayesodot/root:temp
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DHuser }}
        # Container registry password
        password: ${{ secrets.DHpass }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
       
    - name: Push container
      run: docker push qayesodot/root:temp

  publish:
    
    needs: release

    runs-on: self-hosted

    steps:
    - name: ssh command
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}


    # steps:
    #   - name: executing remote ssh commands using password
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USERNAME }}
    #       password: ${{ secrets.PASSWORD }}
    #       port: ${{ secrets.PORT }}
    #       script_stop: true
    #       script: echo check, 1 2, please work dont die on me


            
