name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag root:temp
    
    - name: Docker Login 
      uses: azure/docker-login@v1
      with:
       login-server: ${{ secrets.acr_registry }}
       username: ${{ secrets.acr_username }}
       password: ${{ secrets.acr_password }}
       
    - name: Push container
      run: docker push root:temp
